### ISSUE TITLE
Config not read properly on Heroku

### ISSUE THREAD

**Issue by onedanshow** [exceptional/exceptional#33]
For my staging and productions environments, exceptions would only post to Exceptional if config/exceptional.yml was formatted like this:

```
api-key: 1234...
```

or this (where the api key is picked up from the environment variables):

```
staging:
  enabled: true

production:
  enabled: true
```

It did _NOT_ worked like this

```
api-key: <%= ENV['EXCEPTIONAL_API_KEY'] =>
```

or this:

```
api-key: '<%= ENV["EXCEPTIONAL_API_KEY"] %>'
```

or this:

```
staging:
  enabled: true
  api-key: 1234...

production:
  enabled: true
  api-key: 5678...
```

I looked at the config.rb and it appears the latter should work, but it did not for me.  Just in case someone else has the same issue.
