### ISSUE TITLE
Exceptional integration with Sidekiq

### ISSUE THREAD

**Issue by felipeclopes** [exceptional/exceptional#48]
I'm trying to receive sidekiq erros in my e-mail, but i was not able to setup properly my Exceptional to achieve that. I didn't found the information on how to do it anywhere, so I hope you could help me to do it.

Exceptional config:

``` yaml
development:
  enabled: true
  send_to: log
beta:
  enabled: true
  send_to: api
  api-key: 'key'
pilot:
  enabled: true
  send_to: api
  api-key: 'key'
```

Initialization that I use to load the api-key for javascript errors (that are working):

``` ruby
exceptional_config = YAML.load_file(File.join(Rails.root, "config", "exceptional.yml"))[Rails.env]

Encorexp::Application.config.exceptional = exceptional_config
```

Do I have to do anything else to make Exceptional work on pilot/beta environment with sidekiq?

Regards,
